// <auto-generated />
using System;
using DynamicObjectBuilder.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicObjectBuilder.DataAccess.Migrations
{
    [DbContext(typeof(SchemaBuilderDbContext))]
    [Migration("20241002100138_Db")]
    partial class Db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicObjectBuilder.DataAccess.Models.DynamicSchemaModels.DynamicSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DynamicSchema", (string)null);
                });

            modelBuilder.Entity("DynamicObjectBuilder.DataAccess.Models.DynamicSchemaModels.SchemaField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DynamicSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldIdentifer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DynamicSchemaId");

                    b.HasIndex("OwnerId");

                    b.ToTable("SchemaField", (string)null);
                });

            modelBuilder.Entity("DynamicObjectBuilder.DataAccess.Models.DynamicSchemaModels.SchemaField", b =>
                {
                    b.HasOne("DynamicObjectBuilder.DataAccess.Models.DynamicSchemaModels.DynamicSchema", "DynamicSchema")
                        .WithMany()
                        .HasForeignKey("DynamicSchemaId");

                    b.HasOne("DynamicObjectBuilder.DataAccess.Models.DynamicSchemaModels.DynamicSchema", "Owner")
                        .WithMany("Fields")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicSchema");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DynamicObjectBuilder.DataAccess.Models.DynamicSchemaModels.DynamicSchema", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
